log:
    filename: '"alemongo_logs"'
    level: '"info"'
mode: '"release"'
name: '"alemongo"'
server:
    host: '"127.0.0.1"'
    port: '"17187"'
    tokenconfig:
        expires_time: 1ns
        key: '"alemongo"'
smtp:
    from_email: '"2648108535@qq.com"'
    host: '"smtp.qq.com"'
    password: '""'
    port: 587
    provider: '"qq"'
    username: '"2648108535@qq.com"'
