name: "alemongo"
mode: "release"
host: "127.0.0.1"

server:
  port: "17187"
  token: 
    key: "alemongo"
    expires_time: 24

log:
  level: "info"
  filename: "alemongo_logs"

smtp:
  provider: "qq"
  host: "smtp.qq.com"
  port: 587
  username: "lemonade"
  password: "syaborriilwdbfdg"
  from_email: "1715713638@qq.com"