// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/bot/packages/git/branches": {
            "get": {
                "description": "获取应用git所有分支",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用"
                ],
                "summary": "获取应用git所有分支",
                "parameters": [
                    {
                        "type": "string",
                        "description": "bot名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "应用名称",
                        "name": "app_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.BotPackagesGitBranches"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/bot/packages/git/commits": {
            "get": {
                "description": "获取应用git分支提交记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用"
                ],
                "summary": "获取应用git分支提交记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "bot名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "应用名称",
                        "name": "app_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分支名称",
                        "name": "branch_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.BotPackagesGitCommits"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/api/v1/packages/switch": {
            "post": {
                "description": "切换机器人应用到指定的 Git 分支和提交",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "机器人应用"
                ],
                "summary": "切换机器人应用分支",
                "parameters": [
                    {
                        "type": "string",
                        "description": "机器人名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "应用名称",
                        "name": "app_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分支名称",
                        "name": "branch_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提交哈希值",
                        "name": "commit_hash",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "切换成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或应用不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "切换分支失败",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bot/copy": {
            "post": {
                "description": "复制机器人",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "机器人"
                ],
                "summary": "复制机器人",
                "parameters": [
                    {
                        "type": "string",
                        "description": "机器人名",
                        "name": "bot_name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {}
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {}
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {}
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/common/info": {
            "get": {
                "description": "获取环境信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "公共"
                ],
                "summary": "获取环境信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.InfoResponse"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "summary": "登陆接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "429": {
                        "description": "账户已被锁定",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.BaseInfo": {
            "type": "object",
            "properties": {
                "build_time": {
                    "description": "构建时间",
                    "type": "string"
                },
                "version": {
                    "description": "版本号",
                    "type": "string"
                }
            }
        },
        "common.InfoResponse": {
            "type": "object",
            "properties": {
                "base": {
                    "$ref": "#/definitions/common.BaseInfo"
                },
                "browser": {
                    "$ref": "#/definitions/common.ToolInfo"
                },
                "git": {
                    "$ref": "#/definitions/common.ToolInfo"
                },
                "location": {
                    "type": "string"
                },
                "node": {
                    "$ref": "#/definitions/common.ToolInfo"
                },
                "nvm": {
                    "$ref": "#/definitions/common.ToolInfo"
                },
                "start_at": {
                    "type": "string"
                }
            }
        },
        "common.ToolInfo": {
            "type": "object",
            "properties": {
                "installed": {
                    "type": "boolean"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.BotPackagesGitBranchCommitsInfo": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.BotPackagesGitBranches": {
            "type": "object",
            "properties": {
                "branches": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "models.BotPackagesGitCommits": {
            "type": "object",
            "properties": {
                "commits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BotPackagesGitBranchCommitsInfo"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "response.ResCode": {
            "type": "integer",
            "format": "int64",
            "enum": [
                1000,
                1001,
                1002,
                1003,
                1004,
                1005,
                1006,
                1007,
                1008,
                1009,
                1010,
                1011,
                1012,
                1013,
                1014,
                1015,
                1016,
                1017,
                1018,
                1019
            ],
            "x-enum-varnames": [
                "CodeSuccess",
                "CodeServerBusy",
                "CodeInvalidParam",
                "RobotCreateFailed",
                "RobotNameIsEmpty",
                "RobotNotExist",
                "RobotAlreadyExist",
                "RobotConfigNotExist",
                "ReadRobotConfigFailed",
                "ErrorRobotLog",
                "CreateConfigFailed",
                "ConfigNameIsEmpty",
                "ConfigContentIsEmpty",
                "ReadConfigFailed",
                "ConfigFileIsDeleted",
                "DeleteConfigFileFailed",
                "ErrorLogLevel",
                "ErrCreateConfigCatFailed",
                "ErrReadConfigCatFailed",
                "TokenInvalid"
            ]
        },
        "response.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.ResCode"
                },
                "data": {},
                "msg": {},
                "request_code": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "127.0.0.1:17187",
	BasePath:         "http://127.0.0.1:17187/",
	Schemes:          []string{},
	Title:            "这里写标题",
	Description:      "alemongo 机器人面板",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
