// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/login": {
            "post": {
                "summary": "登陆接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "429": {
                        "description": "账户已被锁定",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.ResCode": {
            "type": "integer",
            "format": "int64",
            "enum": [
                1000,
                1001,
                1002,
                1003,
                1004,
                1005,
                1006,
                1007,
                1008,
                1009,
                1010,
                1011,
                1012,
                1013,
                1014,
                1015,
                1016,
                1017,
                1018,
                1019
            ],
            "x-enum-varnames": [
                "CodeSuccess",
                "CodeServerBusy",
                "CodeInvalidParam",
                "RobotCreateFailed",
                "RobotNameIsEmpty",
                "RobotNotExist",
                "RobotAlreadyExist",
                "RobotConfigNotExist",
                "ReadRobotConfigFailed",
                "ErrorRobotLog",
                "CreateConfigFailed",
                "ConfigNameIsEmpty",
                "ConfigContentIsEmpty",
                "ReadConfigFailed",
                "ConfigFileIsDeleted",
                "DeleteConfigFileFailed",
                "ErrorLogLevel",
                "ErrCreateConfigCatFailed",
                "ErrReadConfigCatFailed",
                "TokenInvalid"
            ]
        },
        "response.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/response.ResCode"
                },
                "data": {},
                "msg": {},
                "request_code": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "127.0.0.1:17187",
	BasePath:         "http://127.0.0.1:17187/",
	Schemes:          []string{},
	Title:            "这里写标题",
	Description:      "alemongo 机器人面板",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
